# Generated by Django 5.0.3 on 2024-03-25 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Customer_name', models.CharField(max_length=70)),
                ('Email', models.EmailField(max_length=70, unique=True)),
                ('PhoneNumber', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('Menu_itemID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=70)),
                ('Description', models.TextField(max_length=255)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Amount', models.PositiveBigIntegerField()),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturant.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('Order_item_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Menu_itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturant.menuitem')),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturant.order')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('ReservationID', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('Number_of_guest', models.PositiveIntegerField()),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturant.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('TableID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Capacity', models.PositiveIntegerField()),
                ('Status', models.CharField(max_length=70)),
                ('ReservationID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resturant.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='TableID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturant.table'),
        ),
    ]
