# Generated by Django 5.0.3 on 2024-05-06 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='ReservationID',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='khan',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='TableID',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='khan',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='OrderID',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='khan',
        ),
        migrations.RemoveField(
            model_name='table',
            name='ReservationID',
        ),
        migrations.RemoveField(
            model_name='table',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='table',
            name='khan',
        ),
    ]
