# Generated by Django 5.0.3 on 2024-05-06 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0002_rename_reservationid_reservation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='khan',
        ),
        migrations.AddField(
            model_name='table',
            name='Status',
            field=models.CharField(default='null', max_length=70),
        ),
        migrations.AddField(
            model_name='table',
            name='id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resturant.reservation'),
        ),
    ]
