# Generated by Django 5.0.3 on 2024-03-29 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0002_rename_date_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='ReservationID',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resturant.reservation'),
        ),
    ]
