# Generated by Django 5.0.3 on 2024-04-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0003_alter_table_reservationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='ItemName',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
