# Generated by Django 5.0.3 on 2024-04-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0004_alter_menuitem_itemname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='Price',
            field=models.PositiveBigIntegerField(),
        ),
    ]
