# Generated by Django 5.0.3 on 2024-04-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0005_alter_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
