# Generated by Django 5.0.3 on 2024-04-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0006_alter_orderitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('Regid', models.BigAutoField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
